### ISSUE TITLE
error handling for source update jobs

### ISSUE THREAD

**Issue by RudiKlassen** [reflectoring/infiniboard#41]
If an error occurs while updating a sourceconfig data, the error must be handled in the widget itself (for example by showing an errorflag for a label) and for the quartermaster (for example by logging the error out). The task here is to evaluate and implement a proper way to handle errors within sourceconfig-update-jobs.

**Comment by matthiasbalke** [comment]
How about the following json structure: 
```
{
"data": {
  "status": 500
  },
"errors": [
    {
      message: 'The connection to xyz.com could not be established.'
    }
  ]
}
```

If harvester failes to fetch the data, for whatever reason an error is appended to the `errors` array. This solution should be fairly simple to implement on the backend and client side. If the errors array is unset or empty the client knows everything is good, otherwise a message with an error can be displayed to the end user.
